[package]
name = "fetchy"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
crossterm = "0.27.0"
os_info = "3.7.0"
sysinfo = "0.29.11"
whoami = "1.4.1"
winit = "0.29.4"
